name: 'Validar Terraform'
on:
  push:
    branches: [ "main", "master" ]
jobs:
  terraform-ci:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform